services:
  - type: web
    name: habit-tracker-api
    runtime: node
    region: singapore
    rootDir: server
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npm run start
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CLIENT_URL
        sync: false
      - key: NODE_ENV
        value: production
